### ISSUE TITLE
Bug: Broken link to source

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/Atlas#9]
![image](https://github.com/Vanilla-OS/Atlas/assets/26346867/d1503c7a-43eb-480b-8d94-e42028c15f74)

The current source link in all modules links to https://github.com/undefined

**Comment by mirkobrombin** [comment]
Reset your local storage, I am unable to replicate. I think you have an old local storage so pressing the refresh button does not work, open the devtools -> application tab -> local storage -> the only one -> clean it -> refresh

![image](https://github.com/Vanilla-OS/Atlas/assets/9479903/017212c0-22b1-4e18-bcf7-6b80d995b7ef)

**Comment by GabsEdits** [comment]
> Reset your local storage, I am unable to replicate. I think you have an old local storage so pressing the refresh button does not work, open the devtools -> application tab -> local storage -> the only one -> clean it -> refresh

Yep, It's fine for me too, it might be just browser cache

**Comment by kbdharun** [comment]
Thanks, I refreshed it. Now it works fine.
